version: "3.7"
services:
  vuerouter-vuex:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ..:/app/:delegated
    container_name: vuerouter-vuex